ALTER TABLE recipe ADD COLUMN prep_time_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipe ADD COLUMN cook_time_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipe ADD COLUMN additional_time_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipe ADD COLUMN servings INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipe ADD COLUMN yield TEXT NOT NULL DEFAULT '';
